name: huzz
description: A new Flutter
  project.https://github.com/project-huzz/huzz-app/blob/dev/pubspec.yaml

publish_to: "none"

version: 1.12.0+26

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bottom_navy_bar: ^6.0.0
  connectivity_plus: ^2.1.0
  country_currency_pickers: ^2.0.0
  country_picker: ^2.0.8
  cupertino_icons: ^1.0.2
  currency_picker: ^2.0.8
  dotted_border: ^2.0.0
  expandable: ^5.0.1
  firebase_core: ^2.3.0
  firebase_dynamic_links: ^5.0.7
  firebase_messaging: ^14.1.3
  flag: ^5.0.1
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.2
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^9.1.5
  flutter_masked_text2: ^0.9.1
  flutter_pdfview: ^1.2.1
  flutter_scatter: ^0.2.0
  flutter_svg: ^0.22.0
  get: ^4.5.1
  get_it: ^7.1.3
  google_fonts: ^3.0.1
  http: ^0.13.1
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  local_auth: null
  new_version: ^0.3.0
  number_display: null
  open_file: ^3.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  pdf: ^3.1.0
  pin_code_fields: ^7.3.0
  printing: ^5.7.2
  provider: ^6.0.1
  random_color: ^1.0.6-nullsafety
  share_plus: ^4.0.10
  shared_preferences: ^2.0.5
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.0.0+4
  syncfusion_flutter_charts: ^19.4.40
  syncfusion_flutter_datepicker: ^19.4.40
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  webview_flutter: ^2.0.10
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/huzz_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fontFamily/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fontFamily/DMSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fontFamily/DMSans-Italic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fontFamily/DMSans-MediumItalic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Regular.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fontFamily/Inter-Regular.ttf
