name: huzz
description: A new Flutter project.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.0.0
  intl: ^0.17.0
  get_it: ^7.2.0
  provider: ^6.0.1
  flutter_svg: ^0.22.0
  flutter_dotenv: ^5.0.2

  sleek_circular_slider: ^2.0.1
  get: ^4.5.1
  country_picker: ^2.0.9
  flag: ^5.0.1
  pin_code_fields: ^7.3.0
  http: ^0.13.3
  shared_preferences: ^2.0.7
  bottom_navy_bar: ^6.0.0
  sqflite: ^2.0.1
  country_currency_pickers: ^2.0.0
  number_display: ^3.0.0

  pdf: ^3.6.4
  flutter_pdfview: ^1.2.1

  url_launcher: ^6.0.10
  open_file: ^3.2.1
  local_auth: ^1.1.7
  path_provider: ^2.0.4
  webview_flutter: ^2.0.13
  random_color: ^1.0.6-nullsafety
  flutter_contacts: ^1.1.1+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  image_picker: ^0.8.4+1
  flutter_launcher_icons: ^0.9.2
  # contact_picker: ^0.0.2
  # fluttercontactpicker: ^4.5.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/huzz_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fontFamily/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fontFamily/DMSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fontFamily/DMSans-Italic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fontFamily/DMSans-MediumItalic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Regular.ttf
