name: huzz
description: A new Flutter project.https://github.com/project-huzz/huzz-app/blob/dev/pubspec.yaml

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.11.5+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  get_it: ^7.1.3
  provider: ^6.0.1
  flutter_svg: ^0.22.0
  flutter_dotenv: ^5.0.2

  sleek_circular_slider: ^2.0.1
  get: ^4.5.1
  country_picker: ^2.0.8
  flag: ^5.0.1
  pin_code_fields: ^7.3.0
  http: ^0.13.1
  shared_preferences: ^2.0.5
  bottom_navy_bar: ^6.0.0
  sqflite: ^2.0.0+4
  country_currency_pickers: ^2.0.0
  number_display:

  pdf: ^3.1.0
  flutter_pdfview: ^1.2.1
  printing: ^5.7.2

  local_auth:
  open_file: ^3.1.0
  url_launcher: ^6.0.18
  path_provider: ^2.0.2
  webview_flutter: ^2.0.10
  flutter_contacts: ^1.1.2
  random_color: ^1.0.6-nullsafety

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.3+3
  flutter_launcher_icons: ^0.9.0
  auto_size_text: ^3.0.0
  uuid: ^3.0.5
  connectivity_plus: ^2.1.0
  timer_button: ^2.0.0
  syncfusion_flutter_charts: ^19.4.40
  path: ^1.8.0
  syncfusion_flutter_datepicker: ^19.4.40
  flutter_easyloading: ^3.0.3
  flutter_scatter: ^0.2.0
  flutter_masked_text2: ^0.9.1
  share_plus: ^3.0.4
  dotted_border: ^2.0.0
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^9.1.5
  currency_picker: ^2.0.8
  firebase_dynamic_links: ^4.1.1
  expandable: ^5.0.1
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/huzz_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fontFamily/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fontFamily/DMSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fontFamily/DMSans-Italic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fontFamily/DMSans-MediumItalic.ttf
          style: italic
        - asset: assets/fontFamily/DMSans-Regular.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fontFamily/Inter-Regular.ttf
